"""kiralama_form_no unique ve required constraint ekle

Revision ID: 1a4fb16c4486
Revises: b1c5e3d8f2a9
Create Date: 2026-03-23 12:03:00.574608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4fb16c4486'
down_revision = 'b1c5e3d8f2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kasa_sube_id'))

    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.alter_column('kiralama_form_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_kiralama_kiralama_form_no'), ['kiralama_form_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_kiralama_kiralama_form_no'), type_='unique')
        batch_op.alter_column('kiralama_form_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kasa_sube_id'), ['sube_id'], unique=False)

    # ### end Alembic commands ###
