"""feat: makine finansal raporı - temin döviz kurları eklendi

Revision ID: 2df1e6700383
Revises: 02ce34234641
Create Date: 2026-03-21 01:03:55.140421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df1e6700383'
down_revision = '02ce34234641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temin_doviz_kuru_usd', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('temin_doviz_kuru_eur', sa.Numeric(precision=10, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.drop_column('temin_doviz_kuru_eur')
        batch_op.drop_column('temin_doviz_kuru_usd')

    # ### end Alembic commands ###
