"""add sube_id to araclar

Revision ID: 86804747b45f
Revises: c1a4f0b9d3e2
Create Date: 2026-03-22 01:20:12.203145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86804747b45f'
down_revision = 'c1a4f0b9d3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('araclar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sube_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_araclar_sube_id_subeler'), 'subeler', ['sube_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('araclar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_araclar_sube_id_subeler'), type_='foreignkey')
        batch_op.drop_column('sube_id')

    # ### end Alembic commands ###
