"""operation_log tablosu eklendi

Revision ID: 86fa7edfc602
Revises: acd89e40b436
Create Date: 2026-03-22 16:32:46.469213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fa7edfc602'
down_revision = 'acd89e40b436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_username'))
        batch_op.drop_index(batch_op.f('ix_operation_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_success'))
        batch_op.drop_index(batch_op.f('ix_operation_log_module'))
        batch_op.drop_index(batch_op.f('ix_operation_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_operation_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_log_action'))

    op.drop_table('operation_log')
    # ### end Alembic commands ###
