"""Kiralama olusturma tarihi alanı ekle

Revision ID: acd89e40b436
Revises: c154aecbd3d2
Create Date: 2026-03-22 13:40:10.579763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd89e40b436'
down_revision = 'c154aecbd3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kiralama_olusturma_tarihi', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.drop_column('kiralama_olusturma_tarihi')

    # ### end Alembic commands ###
