"""drop_enerji_kaynagi_column

Revision ID: c154aecbd3d2
Revises: 86804747b45f
Create Date: 2026-03-22 10:06:41.267182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c154aecbd3d2'
down_revision = '86804747b45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.drop_column('enerji_kaynagi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enerji_kaynagi', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
